apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGtlZG5xeXdu
  CLOUDINARY_KEY: NzY1NDgxMTk1MjQ3Nzc2
  CLOUDINARY_SECRET: UXBqRDJ5a1Y0TnpMX3RSX0drc192QWpUeUV3
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZMmhwYm01cE1EQXdJaXdpWVNJNkltTnRiSE14Wld3d2R6QXhaMlV6WlhNeE1HeHRhMmsxZW1jaWZRLmpSYWdYeGlIWEhjSTlPUXpuRXJzLWc=
  DB_URL: bW9uZ29kYitzcnY6Ly9jaGlubmlwc3BrMDAwX2RiX3VzZXI6b0RWcGNJYzhKMXpoSGhicEBjbHVzdGVyMC53YWVyMnF6Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
  SECRET: bXVzdGFmYQ==
